general:
  domain: "attacker.com"
  address: "1.2.3.4"
  logPort: 443

targets:
  - target: "demo"
    script: "web-discover"

  - target: "sysinfo"
    script: "sysinfo"

  - target: "port-scan"
    script: "port-scan"
    args:
      ports:
        - 80
        - 8080
